services:
  api:
    build:
      context: .
      target: development
    container_name: ruckenprobleme-api
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_CONN_STRING=mongodb://root:Randowm1123@mongodb:27020
    volumes:
      - .:/app
      - /app/node_modules
    # command: npm run dev
    command: tail -f /dev/null
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    restart: always
    expose:
      - 27020
    ports:
      - 27020:27020
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Randowm1123
      - MONGO_INITDB_DATABASE=shop
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    #   - ./.db/mongodb:/data/db
    #   - ./.db/mongodb_config:/data/configdb
    command: mongod --port 27020
