services:
  api:
    build:
      context: .
      target: development
    environment:
      - PORT=8080
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=shop
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always