services:
  api:
    build:
      context: .
      target: development
    container_name: ruckenprobleme-api
    expose:
      - 8080
      - 27017
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - DB_CONN_STRING=mongodb://mongodb:27017
    volumes:
      - .:/app
      - /app/node_modules
    # command: npm run dev
    command: tail -f /dev/null
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./.db/mongodb:/data/db
      - ./.db/mongodb_config:/data/configdb
    command: mongod