services:
  api:
    build:
      context: .
      target: development
    container_name: ruckenprobleme-api
    expose:
      - 80
      - 27017
    ports:
      - 80:80
    environment:
      - PORT=80
      - DB_CONN_STRING=mongodb://root:Start123@mongodb:27017
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Start123
    volumes:
      - ./.db/mongodb:/data/db
      - ./.db/mongodb_config:/data/configdb
    command: mongod