version: '3.9'
services:
  api:
    extends:
      file: docker-compose.common.yml
      service: api
    container_name: ruckenprobleme-test-api
    environment:
      - PORT=8080
      - DB_CONN_STRING=mongodb://mongodb:27018
    command: npm run test
    depends_on:
      - mongodb
  mongodb:
    extends:
      file: docker-compose.common.yml
      service: mongodb
    container_name: ruckenprobleme-test-mongodb
    expose:
      - 27018
    ports:
      - 27018:27018
    command: mongod --port 27018 --quiet --logpath /dev/null
    